---
services:
  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: chromium
    security_opt:
      - seccomp:unconfined
    environment:
      - CUSTOM_USER=
      - PASSWORD=
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - LANG=en_US.UTF-8
    volumes:
      - chromium:/config
    ports:
      - 3010:3000
      - 3011:3001
    shm_size: "1gb"
    restart: unless-stopped
    privileged: true

volumes:
  chromium:
    external: true
